# Generated by Django 3.1 on 2022-06-09 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220609_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='last_name',
            new_name='last_names',
        ),
    ]
